#!/usr/bin/env python3
"""
Build the auto-generated index section in README.md from data/restaurants.csv.

Sections generated:
- By area: each area, count + average score
- By list: links to all lists/*.md
- Top 10: sorted by overall score desc
- All restaurants: sorted by overall desc, with cuisine / price / must_order

Only modifies content between <!-- BEGIN AUTOGENERATED --> and <!-- END AUTOGENERATED -->.
Everything else in README.md is preserved.
"""

import csv
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "data" / "restaurants.csv"
README_PATH = ROOT / "README.md"
LISTS_DIR = ROOT / "lists"

BEGIN_MARKER = "<!-- BEGIN AUTOGENERATED -->"
END_MARKER = "<!-- END AUTOGENERATED -->"


def load_restaurants():
    rows = []
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for r in reader:
            # parse numbers
            def to_float(x):
                x = (x or "").strip()
                return float(x) if x else None
            for k in ["taste", "environment", "service", "value", "overall"]:
                r[k] = to_float(r.get(k))
            rows.append(r)
    return rows


def md_link(text, rel_path):
    return f"[{text}]({rel_path})"


def area_table(rows):
    """Group by area, show count + avg overall."""
    by_area = defaultdict(list)
    for r in rows:
        by_area[r["area"]].append(r)

    lines = ["### By area", "", "| 地区 | 店数 | 平均分 |", "|---|---|---|"]
    for area in sorted(by_area.keys()):
        items = by_area[area]
        scores = [r["overall"] for r in items if r["overall"] is not None]
        avg = f"{sum(scores)/len(scores):.1f}" if scores else "—"
        area_cn = items[0].get("area_cn") or area
        lines.append(f"| {area_cn} {area} | {len(items)} | {avg} |")
    lines.append("")
    return "\n".join(lines)


def list_index(rows):
    """List all lists/*.md as links."""
    if not LISTS_DIR.exists():
        return ""
    files = sorted(LISTS_DIR.glob("*.md"))
    lines = ["### By list", ""]
    for f in files:
        # title is first line's "# ..."
        title = f.stem
        first = f.read_text(encoding="utf-8").splitlines()[0].lstrip("# ").strip()
        if first:
            title = first
        lines.append(f"- [{title}](lists/{f.name})")
    lines.append("")
    return "\n".join(lines)


def top_table(rows, n=10):
    """Top N by overall score."""
    scored = [r for r in rows if r["overall"] is not None]
    scored.sort(key=lambda r: r["overall"], reverse=True)
    lines = [f"### Top {n}", "", "> 按综合评分排序，至少吃过一次才会进榜。", "",
             "| # | 店 | 地区 | 菜系 | 分 |", "|---|---|---|---|---|"]
    for i, r in enumerate(scored[:n], 1):
        area = r.get("area_cn") or r["area"]
        cuisine = r.get("cuisine", "").replace(";", " / ")
        link_path = f"restaurants/{r['area']}/{r['slug']}.md"
        lines.append(f"| {i} | {md_link(r['name'], link_path)} | {area} | {cuisine} | {r['overall']:.1f} |")
    lines.append("")
    return "\n".join(lines)


def all_table(rows):
    """All restaurants sorted by overall desc."""
    scored = [r for r in rows if r["overall"] is not None]
    unscored = [r for r in rows if r["overall"] is None]
    scored.sort(key=lambda r: r["overall"], reverse=True)
    ordered = scored + unscored

    lines = ["### All restaurants", "",
             "按综合评分降序。无评分的店列在末尾（如纯外带或已关店）。",
             "", "| # | 店 | 地区 | 菜系 | 价位 | 综合 | 必点 | 最近访问 |",
             "|---|---|---|---|---|---|---|---|"]
    for i, r in enumerate(ordered, 1):
        area = r.get("area_cn") or r["area"]
        cuisine = r.get("cuisine", "").replace(";", " / ")
        price = r.get("price", "") or "—"
        overall = f"{r['overall']:.1f}" if r["overall"] is not None else "—"
        must = r.get("must_order", "") or "—"
        last = r.get("last_visited", "") or "—"
        link = md_link(r["name"], f"restaurants/{r['area']}/{r['slug']}.md")
        lines.append(f"| {i} | {link} | {area} | {cuisine} | {price} | {overall} | {must} | {last} |")
    lines.append("")
    return "\n".join(lines)


def build_section(rows):
    parts = [area_table(rows), list_index(rows), top_table(rows), all_table(rows)]
    return "\n".join(parts).rstrip() + "\n"


def update_readme(new_section):
    text = README_PATH.read_text(encoding="utf-8")
    if BEGIN_MARKER not in text or END_MARKER not in text:
        print(f"ERROR: markers not found in README.md", file=sys.stderr)
        sys.exit(1)
    before = text.split(BEGIN_MARKER)[0]
    after = text.split(END_MARKER)[1]
    new_text = before + BEGIN_MARKER + "\n\n" + new_section + "\n" + END_MARKER + after
    README_PATH.write_text(new_text, encoding="utf-8")


def main():
    rows = load_restaurants()
    section = build_section(rows)
    update_readme(section)
    print(f"Updated README.md with {len(rows)} restaurants.")


if __name__ == "__main__":
    main()
